### ISSUE TITLE
Compatibility with Matlab 2022b

### ISSUE THREAD

**Issue by HannesWitt** [jacobkers/Loeff-Kerssemakers-et-al-AutoStepFinder#1]
Hi, 
we found that the code would not run on Matlab 2022b. The issue was in line 604 and we could fix it by changing it to 
                case 'mean', FitX(ixlo:ixhi)=mean(X(ixlo:ixhi),'omitnan');

Cheers,
Hannes

**Comment by jacobkers** [comment]
Dear Hannes,
I replaced nanmean, nanmedian, nanst including reference to your issue. 
Thank you for pointing this out!

Cheers, Jacob
