### ISSUE TITLE
error in expandsplitlog

### ISSUE THREAD

**Issue by HannesWitt** [jacobkers/Loeff-Kerssemakers-et-al-AutoStepFinder#2]
Hi,
for some data sets the first round of fits would not find any steps which caused an error in the function "expand_split_log" because the 
variable full_split_log would be empty which caused an error in the line 
` already_found=find(full_split_log(:,2)<3);   `

I made a small work around by changing the function to:

function full_split_log=expand_split_log(full_split_log,split_indices,fitround,best_shot)   
           %expand split log; remove double entries (when a residu of a  
           %step is found again, we label the location by its first  
           %round occurence)  
           LS=length(split_indices);  
           new_split_log=[split_indices 3*ones(LS,1)];  
           new_split_log(1:best_shot,2)=fitround;            
               if fitround==1  
                    full_split_log=[full_split_log ; new_split_log];  
               else  
                   if ~isempty(full_split_log)   
                   already_found=find(full_split_log(:,2)<3);  %steps already spotted   
                    new_found=find(~ismember(new_split_log(:,1),full_split_log(already_found,1)));                     
                    full_split_log= [full_split_log(already_found,:);...   
                                     new_split_log(new_found,:)];   
                   else   
                    full_split_log= [full_split_log;new_split_log];  
                   end  
               end

**Comment by jacobkers** [comment]
Dear Hannes,

Thank you for pointing out and solving. I took over your solution including credits

Cheers, Jacob
